routes/web.php
<?php



use Illuminate\Routing\RouteGroup;
use Illuminate\Contracts\Queue\Job;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\jobcontroller;

use Illuminate\Support\Facades\Session;



use App\Http\Controllers\HomeController;
use App\Http\Controllers\itemController;
use App\Http\Controllers\sellController;
use App\Http\Controllers\loginController;
use App\Http\Controllers\summaryController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\CompaniesController;
use App\Http\Controllers\LocalizationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middleware' => ['auth']], function () {
    
    //route For home
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::get('/home', [HomeController::class, 'index'])->name('home');
    
    // route for companies using companies controller
    Route::get('/companies', [CompaniesController::class, 'index'])->name('companies');
    Route::get('/inputcompanies', [CompaniesController::class, 'create'])->name('inputcomp');
    Route::post('/submitcompanies', [CompaniesController::class, 'store'])->name('submitcomp');
    Route::get('/editcompanies/{id}', [CompaniesController::class, 'edit'])->name('editcomp');
    Route::put('/updatecompanies/{id}', [CompaniesController::class, 'update'])->name('updatecomp');
    Route::get('/companies/{id}', [CompaniesController::class, 'destroy'])->name('deletecomp');
    Route::get('/searchcompanies', [CompaniesController::class, 'search'])->name('searchcomp');
    
    
    // route for employee using employee controller
    Route::get('/employee', [EmployeeController::class, 'index'])->name('employee');
    Route::get('/inputemployee', [EmployeeController::class, 'create'])->name('inputemplo');
    Route::post('/submitemployee', [EmployeeController::class, 'store'])->name('submitemplo');
    Route::get('/editemployee/{id}', [EmployeeController::class, 'edit'])->name('editemplo');
    Route::put('/updateemployee/{id}', [EmployeeController::class, 'update'])->name('updateemplo');
    Route::get('/deleteemployee/{id}', [EmployeeController::class, 'destroy'])->name('deleteemplo');
    Route::get('/searchemployee', [EmployeeController::class, 'search'])->name('searchemplo');
    
    
    // route for item page
    Route::get('/items', [itemController::class, 'index'])->name('item');
    Route::get('/inputitems', [itemController::class, 'create'])->name('inputitems'); // for input item
    Route::post('/submititems', [itemController::class, 'store'])->name('submititems'); // for submit to db item
    Route::get('/edititems/{id}', [itemController::class, 'edit'])->name('edititems'); // for edit to db item
    Route::put('/updateitems/{id}', [itemController::class, 'update'])->name('updateitems'); // for update to db item
    Route::get('/deleteitems/{id}', [itemController::class, 'destroy'])->name('deleteitems'); // for delete to db item
    Route::get('/searchitems', [itemController::class, 'search'])->name('searchitems'); // for search item
    
    // Route for sell page
    Route::get('/sell', [sellController::class, 'index'])->name('sell');
    Route::get('/inputsell', [sellController::class, 'create'])->name('inputsell'); // for input sell
    Route::post('/submitsell', [sellController::class, 'store'])->name('submitsell'); // for input sell
    Route::get('/editsell/{id}', [sellController::class, 'edit'])->name('editsell'); // for input sell
    Route::put('/updatesell/{id}', [sellController::class, 'update'])->name('updatesell'); // for input sell
    Route::get('/deletesell/{id}', [sellController::class, 'destroy'])->name('deletesell'); // for delete sell
    Route::get('/searchsell', [sellController::class, 'search'])->name('searchsell'); // for search sell
    
    
    
    // Route for summary page
    Route::get('/summary', [summaryController::class, 'index'])->name('summary');
    Route::get('/detailsummary/{id}', [summaryController::class, 'detail'])->name('detailsummary'); 
    Route::get('/searchsummary', [summaryController::class, 'search'])->name('searchsummary'); 
    
    
    // Route for mail
    Route::get('test-email', [jobcontroller::class, 'enqueue'])->name('test-email');
    
    
    
    
    // Route for Language
    if (file_exists(app_path('Http/Controllers/LocalizationController.php')))
    {
        Route::get('/locale/{locale}', [LocalizationController::class , 'locale'])->name('locale');
    }
    
    // Route for timezone
    Route::get('tz/{tz}', ['as' => 'tz.switch', 'uses' => App\Http\Controllers\datetimeController::class, 'switch']);
});



// Route for login
Route::get('/login',[loginController::class,'index'])->name('login')->middleware('guest');
Route::post('/loginuser',[loginController::class,'loginuser'])->name('loginuser');
Route::post('/logout',[loginController::class,'logout'])->name('logout');

app/Models/employee.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Session;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class employee extends Model
{
    use HasFactory;
    // make protected
    protected $table = 'employees';
    protected $primaryKey = 'id';
    protected $fillable = [
        'name',
        'password',
        'company_id',
        'city',
        'phone',
        'email',
        'created_users_id',
        'updated_users_id',
       
    ];

    public function Rcompany()
    {
        return $this->belongsTo(companies::class, 'company_id')->withDefault();
    }

    public function Rsell()
    {
        return $this->hasMany(sell::class);
    }

    public function Rsummaries()
    {
        return $this->hasMany(sellsummaries::class);
    }

    public function getCreatedAtAttribute($value)
    {
       return Carbon::createFromTimestamp(strtotime($value))
        ->timezone(Session::get('tz'))
        ->toDateTimeString();
    }
    
    public function getUpdatedAtAttribute($value)
    {
       return Carbon::createFromTimestamp(strtotime($value))
        ->timezone(Session::get('tz'))
        ->toDateTimeString();
    }


    
   
   
}

resources/views/companies.blade.php
@extends('layouts.main')

@section('lyts')
<h2>{{ trans('companies.listcompany') }}</h2>

{{-- CRUD DROPDOWN --}}
<div class="dropdown" aria-labelledby="navbarDropdown" style="float:right; ">
  <button class="dropbtn"><h4>+</h4></button>
  <div class="dropdown-content  dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" style="float:right; oveflow: auto; max-heiht:200px;">
    <a href="/inputcompanies" class="dropdown-item" >{{ trans('companies.company') }}</a>
    <a href="/inputemployee" class="dropdown-item" >{{ trans('companies.employe') }}</a>
    <a href="/inputitems" class="dropdown-item" >{{ trans('companies.items') }}</a>
    <a href="/inputsell" class="dropdown-item" >{{ trans('companies.sell') }}</a>
  </div>
</div>
{{-- END CRUD DROPDOWN --}}

{{-- Search --}}
<form action="{{ route('searchcomp') }}" method="GET">
 
  <input type="search" id="myInput"  placeholder="Name" name="company_name" value="{{ request('company_name') }}">
  <input type="search" id="myInput2"  placeholder="Address" name="address" value="{{ request('address') }}">
  <input type="search" id="myInput3"  placeholder="City" name="city" value="{{ request('city') }}">
  <input type="search" id="myInput4"  placeholder="Country" name="country" value="{{ request('country') }}">
  <input type="date" id="myInput5"  name="start_date" value="{{ request('start_date') }}">
  <input type="date" id="myInput6"  name="end_date" value="{{ request('end_date') }}">
  <button class="btn btn-primary" type="submit">Search</button>
  
</form>
{{-- END SEARCH --}}


{{-- TABLE CONTENT --}}
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <table class="table table-bordered table-hover dt-responsive text-center" id="myTable" >
        <thead>
          <tr>
            <th class="bg-primary text-center" >{{ trans('companies.name') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.address') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.city') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.country') }}</th>
            <th class="bg-primary text-center">Logo</th>
            <th class="bg-primary text-center">{{ trans('companies.createdat') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.updatedat') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.action') }}</th>
          </tr>
        </thead>
        <tbody>
            @foreach($companies as $cps)
            <tr>
                <td>{{ $cps->company_name }}</td>
                <td>{{ $cps->address }}</td>
                <td>{{ $cps->city }}</td>
                <td>{{ $cps->country }}</td>
                @if ($cps->image)
                  <td><img src="{{ asset('storage/'.$cps->image) }}" alt="" style="max-height: 100px"></td>                    
                @else
                  <td>-</td>
                @endif
                <td>{{ $cps->created_at}}</td>
                <td>{{ $cps->updated_at }}</td>
                <td>
                  <a href="{{ route('editcomp', $cps->id) }}" class="btn btn-success p-1 mb-1">{{ trans('companies.edit') }}</a>  | <a href="{{ route('deletecomp', $cps->id) }}" class="btn btn-warning">{{ trans('companies.delete') }} </a>
                </td>
            </tr>
            @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- partial -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='https://cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js'></script>
<script src='https://cdn.datatables.net/plug-ins/f2c75b7247b/integration/bootstrap/3/dataTables.bootstrap.js'></script>
<script src='https://cdn.datatables.net/responsive/1.0.4/js/dataTables.responsive.js'></script>
<script  src="../js/script.js"></script>
@endsection

resources/views/employee.blade.php
@extends('layouts.main')

@section('lyts')
<h2>{{ trans('companies.listemploye') }}</h2>

{{-- CRUD DROPDOWN --}}
<div class="dropdown" aria-labelledby="navbarDropdown" style="float:right; ">
  <button class="dropbtn"><h4>+</h4></button>
  <div class="dropdown-content  dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" style="float:right; oveflow: auto; max-heiht:200px;">
    <a href="/inputcompanies" class="dropdown-item" >{{ trans('companies.company') }}</a>
    <a href="/inputemployee" class="dropdown-item" >{{ trans('companies.employe') }}</a>
    <a href="/inputitems" class="dropdown-item" >{{ trans('companies.items') }}</a>
    <a href="/inputsell" class="dropdown-item" >{{ trans('companies.sell') }}</a>
  </div>
</div>
{{-- END CRUD DROPDOWN --}}

{{-- search --}}
<form action="{{ route("searchemplo") }}" method="GET">
  @csrf
  <input type="text" id="myem"  placeholder="Name" name="name" value="{{ request('name') }}">
  <select  id="myem2" name="company" >
    <option value=""> Select Company</option>
    @foreach ($companies as $cps)
      <option value="{{ $cps->id}}" {{ request('company') == $cps->id ? 'selected' : null }}>{{ $cps->company_name }}</option>
    @endforeach
  </select>
  <input type="text" id="myem3"  placeholder="City" name="city" value="{{ request('city') }}">
  <input type="text" id="myem4"  placeholder="Phone" name="phone" value="{{ request('phone') }}">
  <input type="text" id="myem2"  placeholder="Email" name="email" value="{{ request('email') }}">
  <input type="date" id="myem5"  name="start_date" value="{{ request('start_date') }}">
  <input type="date" id="myem6"  name="end_date" value="{{ request('end_date') }}">
  <button class="btn btn-primary" type="submit">Search</button>
  
</form>
{{-- end search --}}


{{-- TABLE CONTENT --}}
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <table class="table table-bordered table-hover dt-responsive text-center">
        <thead>
          <tr>
            <th class="bg-primary text-center">{{ trans('companies.name') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.company') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.city') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.phone') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.email') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.createdat') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.updatedat') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.action') }}</th>
          </tr>
        </thead>
        <tbody>
            @foreach($employee as $emp)
            <tr>
                <td>{{ $emp->name }}</td>
                <td>{{ $emp->Rcompany->company_name }}</td>
                <td>{{ $emp->city }}</td>
                <td>{{ $emp->phone }}</td>
                <td>{{ $emp->email }}</td>
                <td>{{ $emp->created_at }}</td>
                <td>{{ $emp->updated_at }}</td>
                
                <td>
                    <a href="{{ route('editemplo', $emp->id) }}" class="btn btn-success p-1 mb-1">{{ trans('companies.edit') }}</a>  | <a href="{{ route('deleteemplo', $emp->id) }}" class="btn btn-warning">{{ trans('companies.delete') }}</a>
                </td>
            </tr>
            @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- partial -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='https://cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js'></script>
<script src='https://cdn.datatables.net/plug-ins/f2c75b7247b/integration/bootstrap/3/dataTables.bootstrap.js'></script>
<script src='https://cdn.datatables.net/responsive/1.0.4/js/dataTables.responsive.js'></script>
<script  src="../js/script.js"></script>
@endsection

resources/views/home.blade.php
@extends('layouts.main')

@section('lyts')
    <h1>Hallo world</h1>
@endsection

resources/views/items.blade.php
@extends('layouts.main')

@section('lyts')
<h2>{{ trans('companies.listitems') }}</h2>

{{-- CRUD DROPDOWN --}}
<div class="dropdown" aria-labelledby="navbarDropdown" style="float:right; ">
  <button class="dropbtn"><h4>+</h4></button>
  <div class="dropdown-content  dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" style="float:right; oveflow: auto; max-heiht:200px;">
    <a href="/inputcompanies" class="dropdown-item" >{{ trans('companies.company') }}</a>
    <a href="/inputemployee" class="dropdown-item" >{{ trans('companies.employe') }}</a>
    <a href="/inputitems" class="dropdown-item" >{{ trans('companies.items') }}</a>
    <a href="/inputsell" class="dropdown-item" >{{ trans('companies.sell') }}</a>
  </div>
</div>
{{-- END CRUD DROPDOWN --}}


{{-- SEARCH FILTER --}}
<form action="{{ route('searchitems') }}" method="GET">

  <input type="text" name="name" id="myem"  placeholder="Name" value="{{ request('name') }}">
  <input type="number" name="price" id="myem3"  placeholder="Price" value="{{ request('price') }}">
  <button class="btn btn-primary" type="submit">Search</button>
  
</form>
{{-- END SEARCH FILTER --}}

{{-- TABLE CONTENT --}}
<div class="container">
  <div class="row">
    @if (session()->has('status'))
    <h3 style="text-align: center">
        {{ session('status') }}
    </h3>
        
    @endif
    <div class="col-xs-12">
      <table class="table table-bordered table-hover dt-responsive text-center">
        <thead>
          <tr>
            <th class="bg-primary text-center" >{{ trans('companies.name') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.price') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.action') }}</th>
          </tr>
        </thead>
        <tbody>
            @foreach($items as $item)
            <tr>
                <td>{{ $item->name }}</td>
                <td>{{ number_format($item->price) }}</td>
                <td>
                    <a href="{{ url('edititems',$item->id) }}" class="btn btn-success p-1 mb-1">{{ trans('companies.edit') }}</a>  | <a href="{{ url('deleteitems', $item->id)}}" class="btn btn-warning">{{ trans('companies.delete') }} </a>
                </td>
            </tr>
            @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- partial -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='https://cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js'></script>
<script src='https://cdn.datatables.net/plug-ins/f2c75b7247b/integration/bootstrap/3/dataTables.bootstrap.js'></script>
<script src='https://cdn.datatables.net/responsive/1.0.4/js/dataTables.responsive.js'></script>
<script  src="../js/script.js"></script>
@endsection

resources/views/sell.blade.php
@extends('layouts.main')

@section('lyts')
<h2>{{ trans('companies.listsell') }}</h2>

{{-- CRUD DROPDOWN --}}
<div class="dropdown" aria-labelledby="navbarDropdown" style="float:right; ">
  <button class="dropbtn"><h4>+</h4></button>
  <div class="dropdown-content  dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" style="float:right; oveflow: auto; max-heiht:200px;">
    <a href="/inputcompanies" class="dropdown-item" >{{ trans('companies.company') }}</a>
    <a href="/inputemployee" class="dropdown-item" >{{ trans('companies.employe') }}</a>
    <a href="/inputitems" class="dropdown-item" >{{ trans('companies.items') }}</a>
    <a href="/inputsell" class="dropdown-item" >{{ trans('companies.sell') }}</a>
  </div>
</div>
{{-- END CRUD DROPDOWN --}}

{{-- search --}}
<form action="{{ route("searchsell") }}" method="GET">

  <select  id="mysell" name="item_id" >
    <option value="">Select Items</option>
    @foreach ($items as $item)
      <option value="{{ $item->id}}" {{ request('item_id') == $item->id ? 'selected' : NULL }}>{{ $item->name }}</option>
    @endforeach
  </select>
  <input type="search" id="mysell2"  placeholder="Price" name="price" value="{{ request('price') }}">
  <input type="search" id="mysell3"  placeholder="Discount (%)" name="discount" value="{{ request('discount') }}">
  <select  id="mysell4" name="employee_id" >
    <option value="">Select Employee</option>
    @foreach ($employees as $ep)
    <option value="{{ $ep->id}}" {{ request('employee_id') == $ep->id ? 'selected' : NULL }}>{{ $ep->name }}</option>
    @endforeach
  </select>
  <input type="date" id="mysell5"  name="start_date" value="{{ request('start_date') }}">
  <input type="date" id="mysell6"  name="end_date" value="{{ request('end_date') }}">
  <button class="btn btn-primary" type="submit">Search</button>
  
</form>
{{-- end search --}}

{{-- TABLE CONTENT --}}
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <table class="table table-bordered table-hover dt-responsive text-center">
        <thead>
          <tr>
            <th class="bg-primary text-center" >{{ trans('companies.date') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.name') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.price') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.discount') }} (%)</th>
            <th class="bg-primary text-center">{{ trans('companies.employe') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.action') }}</th>
          </tr>
        </thead>
        <tbody>
          @foreach($sells as $sell)
            <tr>
              <td>{{ $sell->created_date }}</td>
              <td>{{ $sell->Sitem->name }}</td>
              <td>{{ number_format($sell->price) }}</td>
              <td>{{ $sell->discount }}</td>
              <td>{{ $sell->Semploy->name }}</td>
              <td>
                <a href="{{ route('editsell',$sell->id) }}" class="btn btn-success p-1 mb-1">{{ trans('companies.edit') }}</a>  | <a href="{{ route('deletesell', $sell->id) }}" class="btn btn-warning">{{ trans('companies.delete') }} </a>
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- partial -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='https://cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js'></script>
<script src='https://cdn.datatables.net/plug-ins/f2c75b7247b/integration/bootstrap/3/dataTables.bootstrap.js'></script>
<script src='https://cdn.datatables.net/responsive/1.0.4/js/dataTables.responsive.js'></script>
<script  src="../js/script.js"></script>
@endsection

resources/views/summary.blade.php
@extends('layouts.main')

@section('lyts')

<?php 
use Carbon\Carbon;
?>
<h2>{{ trans('companies.listsummary') }}</h2>

{{-- search --}}
<form action="{{ route('searchsummary') }}" method="GET">

  <input list="comp" id="mys3"  placeholder="Companies" name="companies">
  <datalist id="comp">
    @foreach($comp as $cp)
    <option value="{{ $cp->company_name}}" {{ request('companies') == $cp->company_name ? 'selected' : NULL }}>{{ $cp->company_name}}</option>
    @endforeach
  </datalist>
  <input list="emp" id="mys4"  placeholder="Employee" name="employee">
  <datalist id="emp">
    @foreach($employees as $emp)
    <option value="{{ $emp->name }}" {{ request('employee') == $emp->name ? 'selected' : NULL }}>{{ $emp->name }}</option>
    @endforeach
  </datalist>
  <input type="date" id="mys5"  name="start_date" value="{{ request('start_date') }}">
  <input type="date" id="mys6"  name="end_date" value="{{ request('end_date') }}">
  <button class="btn btn-primary" type="submit">Search</button>
  
</form>
{{-- end search --}}


{{-- TABLE CONTENT --}}
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <table class="table table-bordered table-hover dt-responsive text-center">
        <thead>
          <tr>
            <th class="bg-primary text-center" >{{ trans('companies.date') }}</th>
            <th class="bg-primary text-center" >{{ trans('companies.company') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.employe') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.createdat') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.lastupdate') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.pricetotal') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.discounttotal') }}</th>
            <th class="bg-primary text-center">{{ trans('companies.total') }}</th>
          
          </tr>
        </thead>
        <tbody>
            @foreach($sellsummaries as $ssm)
            <tr>
                <td><a href="{{ route('detailsummary', $ssm->id) }}">{{ Carbon::parse($ssm->date)->format('Y-m-d')}} </a></td>
                <td>{{ $ssm->SSemploy->Rcompany->company_name}}</td>
                <td>{{ $ssm->SSemploy->name }}</td>
                <td>{{ $ssm->created_at}}</td>
                <td>{{ $ssm->updated_at }}</td>
                <td>{{ number_format( $ssm->price_total) }}</td>
                <td>{{ number_format($ssm->discount_total) }}</td>
                <td>{{ number_format($ssm->total) }}</td>
            </tr>
            @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>

<!-- partial -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='https://cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js'></script>
<script src='https://cdn.datatables.net/plug-ins/f2c75b7247b/integration/bootstrap/3/dataTables.bootstrap.js'></script>
<script src='https://cdn.datatables.net/responsive/1.0.4/js/dataTables.responsive.js'></script>
<script  src="../js/script.js"></script>
@endsection